name: chance_dart
description: Chance Dart is a free Open Source project that lets you create random strings, integers, and other things to help with tiresome tasks, especially when building automated tests or wherever else you require anything random.
version: 0.0.1+1
homepage: https://github.com/Yczar/chance-dart

environment:
  sdk: ">=2.16.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  chance_generator: any
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
  dart_code_metrics: ^5.0.1

dependencies:
  dart_geohash: ^2.0.2
  equatable: ^2.0.5
  meta: ^1.8.0
